// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: proto/TodoItem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TodoItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc     string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	DaysLeft *int32 `protobuf:"varint,4,opt,name=days_left,json=daysLeft,proto3,oneof" json:"days_left,omitempty"`
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{0}
}

func (x *TodoItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TodoItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *TodoItem) GetDaysLeft() int32 {
	if x != nil && x.DaysLeft != nil {
		return *x.DaysLeft
	}
	return 0
}

type ListTodoItemFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *string `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
}

func (x *ListTodoItemFilterRequest) Reset() {
	*x = ListTodoItemFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTodoItemFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodoItemFilterRequest) ProtoMessage() {}

func (x *ListTodoItemFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodoItemFilterRequest.ProtoReflect.Descriptor instead.
func (*ListTodoItemFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{1}
}

func (x *ListTodoItemFilterRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

type GetTodoItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTodoItemRequest) Reset() {
	*x = GetTodoItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoItemRequest) ProtoMessage() {}

func (x *GetTodoItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoItemRequest.ProtoReflect.Descriptor instead.
func (*GetTodoItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{2}
}

func (x *GetTodoItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTodoItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *TodoItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetTodoItemResponse) Reset() {
	*x = GetTodoItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoItemResponse) ProtoMessage() {}

func (x *GetTodoItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoItemResponse.ProtoReflect.Descriptor instead.
func (*GetTodoItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoItemResponse) GetItem() *TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateTodoItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc     string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	DaysLeft *int32 `protobuf:"varint,3,opt,name=days_left,json=daysLeft,proto3,oneof" json:"days_left,omitempty"`
}

func (x *CreateTodoItemRequest) Reset() {
	*x = CreateTodoItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTodoItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoItemRequest) ProtoMessage() {}

func (x *CreateTodoItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoItemRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTodoItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTodoItemRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateTodoItemRequest) GetDaysLeft() int32 {
	if x != nil && x.DaysLeft != nil {
		return *x.DaysLeft
	}
	return 0
}

type UpdateTodoItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Item *TodoItem `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *UpdateTodoItemRequest) Reset() {
	*x = UpdateTodoItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTodoItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoItemRequest) ProtoMessage() {}

func (x *UpdateTodoItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTodoItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTodoItemRequest) GetItem() *TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteTodoItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *TodoItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *DeleteTodoItemRequest) Reset() {
	*x = DeleteTodoItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTodoItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoItemRequest) ProtoMessage() {}

func (x *DeleteTodoItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTodoItemRequest) GetItem() *TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteTodoItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTodoItemResponse) Reset() {
	*x = DeleteTodoItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TodoItem_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTodoItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoItemResponse) ProtoMessage() {}

func (x *DeleteTodoItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TodoItem_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteTodoItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_TodoItem_proto_rawDescGZIP(), []int{7}
}

var File_proto_TodoItem_proto protoreflect.FileDescriptor

var file_proto_TodoItem_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x20, 0x0a, 0x09, 0x64, 0x61,
	0x79, 0x73, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x08, 0x64, 0x61, 0x79, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x64, 0x61, 0x79, 0x73, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x22, 0x43, 0x0a, 0x19, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x6f, 0x64,
	0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x6f, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x20, 0x0a, 0x09,
	0x64, 0x61, 0x79, 0x73, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x08, 0x64, 0x61, 0x79, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0c,
	0x0a, 0x0a, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x22, 0x46, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x22, 0x36, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x18, 0x0a, 0x16,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xad, 0x02, 0x0a, 0x0b, 0x54, 0x6f, 0x64, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x2f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65,
	0x6d, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64,
	0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x6f, 0x42, 0x0a, 0x50, 0x6f, 0x6e, 0x79, 0x63,
	0x6f, 0x70, 0x74, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_TodoItem_proto_rawDescOnce sync.Once
	file_proto_TodoItem_proto_rawDescData = file_proto_TodoItem_proto_rawDesc
)

func file_proto_TodoItem_proto_rawDescGZIP() []byte {
	file_proto_TodoItem_proto_rawDescOnce.Do(func() {
		file_proto_TodoItem_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_TodoItem_proto_rawDescData)
	})
	return file_proto_TodoItem_proto_rawDescData
}

var file_proto_TodoItem_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_TodoItem_proto_goTypes = []interface{}{
	(*TodoItem)(nil),                  // 0: TodoItem
	(*ListTodoItemFilterRequest)(nil), // 1: ListTodoItemFilterRequest
	(*GetTodoItemRequest)(nil),        // 2: GetTodoItemRequest
	(*GetTodoItemResponse)(nil),       // 3: GetTodoItemResponse
	(*CreateTodoItemRequest)(nil),     // 4: CreateTodoItemRequest
	(*UpdateTodoItemRequest)(nil),     // 5: UpdateTodoItemRequest
	(*DeleteTodoItemRequest)(nil),     // 6: DeleteTodoItemRequest
	(*DeleteTodoItemResponse)(nil),    // 7: DeleteTodoItemResponse
}
var file_proto_TodoItem_proto_depIdxs = []int32{
	0, // 0: GetTodoItemResponse.item:type_name -> TodoItem
	0, // 1: UpdateTodoItemRequest.item:type_name -> TodoItem
	0, // 2: DeleteTodoItemRequest.item:type_name -> TodoItem
	1, // 3: TodoService.ListTodoItems:input_type -> ListTodoItemFilterRequest
	2, // 4: TodoService.GetTodoItem:input_type -> GetTodoItemRequest
	4, // 5: TodoService.CreateTodoItem:input_type -> CreateTodoItemRequest
	5, // 6: TodoService.UpdateTodoItem:input_type -> UpdateTodoItemRequest
	6, // 7: TodoService.DeleteTodoItem:input_type -> DeleteTodoItemRequest
	0, // 8: TodoService.ListTodoItems:output_type -> TodoItem
	0, // 9: TodoService.GetTodoItem:output_type -> TodoItem
	0, // 10: TodoService.CreateTodoItem:output_type -> TodoItem
	0, // 11: TodoService.UpdateTodoItem:output_type -> TodoItem
	7, // 12: TodoService.DeleteTodoItem:output_type -> DeleteTodoItemResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_TodoItem_proto_init() }
func file_proto_TodoItem_proto_init() {
	if File_proto_TodoItem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_TodoItem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TodoItem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTodoItemFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TodoItem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TodoItem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TodoItem_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTodoItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TodoItem_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTodoItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TodoItem_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTodoItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TodoItem_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTodoItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_TodoItem_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_TodoItem_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_TodoItem_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_TodoItem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_TodoItem_proto_goTypes,
		DependencyIndexes: file_proto_TodoItem_proto_depIdxs,
		MessageInfos:      file_proto_TodoItem_proto_msgTypes,
	}.Build()
	File_proto_TodoItem_proto = out.File
	file_proto_TodoItem_proto_rawDesc = nil
	file_proto_TodoItem_proto_goTypes = nil
	file_proto_TodoItem_proto_depIdxs = nil
}
