// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: TodoItem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TodoItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc     string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	DaysLeft int32  `protobuf:"varint,4,opt,name=days_left,json=daysLeft,proto3" json:"days_left,omitempty"`
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{0}
}

func (x *TodoItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TodoItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *TodoItem) GetDaysLeft() int32 {
	if x != nil {
		return x.DaysLeft
	}
	return 0
}

type GetTodoItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetTodoItemsRequest) Reset() {
	*x = GetTodoItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoItemsRequest) ProtoMessage() {}

func (x *GetTodoItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoItemsRequest.ProtoReflect.Descriptor instead.
func (*GetTodoItemsRequest) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{1}
}

func (x *GetTodoItemsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTodoItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []*TodoItem `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *GetTodoItemsResponse) Reset() {
	*x = GetTodoItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTodoItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoItemsResponse) ProtoMessage() {}

func (x *GetTodoItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoItemsResponse.ProtoReflect.Descriptor instead.
func (*GetTodoItemsResponse) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{2}
}

func (x *GetTodoItemsResponse) GetItem() []*TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateTodoItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *TodoItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreateTodoItemRequest) Reset() {
	*x = CreateTodoItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTodoItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoItemRequest) ProtoMessage() {}

func (x *CreateTodoItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoItemRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoItemRequest) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTodoItemRequest) GetItem() *TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateTodoItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTodoItemResponse) Reset() {
	*x = CreateTodoItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTodoItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoItemResponse) ProtoMessage() {}

func (x *CreateTodoItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoItemResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoItemResponse) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{4}
}

type UpdateTodoItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTodoItemRequest) Reset() {
	*x = UpdateTodoItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTodoItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoItemRequest) ProtoMessage() {}

func (x *UpdateTodoItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoItemRequest) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{5}
}

type UpdateTodoItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTodoItemResponse) Reset() {
	*x = UpdateTodoItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTodoItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoItemResponse) ProtoMessage() {}

func (x *UpdateTodoItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoItemResponse) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{6}
}

type DeleteTodoItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTodoItemRequest) Reset() {
	*x = DeleteTodoItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTodoItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoItemRequest) ProtoMessage() {}

func (x *DeleteTodoItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoItemRequest) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{7}
}

type DeleteTodoItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTodoItemResponse) Reset() {
	*x = DeleteTodoItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TodoItem_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTodoItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoItemResponse) ProtoMessage() {}

func (x *DeleteTodoItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TodoItem_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteTodoItemResponse) Descriptor() ([]byte, []int) {
	return file_TodoItem_proto_rawDescGZIP(), []int{8}
}

var File_TodoItem_proto protoreflect.FileDescriptor

var file_TodoItem_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x5f, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61,
	0x79, 0x73, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64,
	0x61, 0x79, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x22, 0x3a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x3b, 0x0a, 0x15,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64,
	0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc2, 0x02, 0x0a, 0x0b, 0x54, 0x6f,
	0x64, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64,
	0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x6f, 0x64, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27,
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f,
	0x6f, 0x42, 0x0a, 0x50, 0x6f, 0x6e, 0x79, 0x63, 0x6f, 0x70, 0x74, 0x65, 0x72, 0x50, 0x01, 0x5a,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TodoItem_proto_rawDescOnce sync.Once
	file_TodoItem_proto_rawDescData = file_TodoItem_proto_rawDesc
)

func file_TodoItem_proto_rawDescGZIP() []byte {
	file_TodoItem_proto_rawDescOnce.Do(func() {
		file_TodoItem_proto_rawDescData = protoimpl.X.CompressGZIP(file_TodoItem_proto_rawDescData)
	})
	return file_TodoItem_proto_rawDescData
}

var file_TodoItem_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_TodoItem_proto_goTypes = []interface{}{
	(*TodoItem)(nil),               // 0: grpc.TodoItem
	(*GetTodoItemsRequest)(nil),    // 1: grpc.GetTodoItemsRequest
	(*GetTodoItemsResponse)(nil),   // 2: grpc.GetTodoItemsResponse
	(*CreateTodoItemRequest)(nil),  // 3: grpc.CreateTodoItemRequest
	(*CreateTodoItemResponse)(nil), // 4: grpc.CreateTodoItemResponse
	(*UpdateTodoItemRequest)(nil),  // 5: grpc.UpdateTodoItemRequest
	(*UpdateTodoItemResponse)(nil), // 6: grpc.UpdateTodoItemResponse
	(*DeleteTodoItemRequest)(nil),  // 7: grpc.DeleteTodoItemRequest
	(*DeleteTodoItemResponse)(nil), // 8: grpc.DeleteTodoItemResponse
}
var file_TodoItem_proto_depIdxs = []int32{
	0, // 0: grpc.GetTodoItemsResponse.item:type_name -> grpc.TodoItem
	0, // 1: grpc.CreateTodoItemRequest.item:type_name -> grpc.TodoItem
	1, // 2: grpc.TodoService.GetTodoItem:input_type -> grpc.GetTodoItemsRequest
	3, // 3: grpc.TodoService.CreateTodoItem:input_type -> grpc.CreateTodoItemRequest
	5, // 4: grpc.TodoService.UpdateTodoItem:input_type -> grpc.UpdateTodoItemRequest
	7, // 5: grpc.TodoService.DeleteTodoItem:input_type -> grpc.DeleteTodoItemRequest
	2, // 6: grpc.TodoService.GetTodoItem:output_type -> grpc.GetTodoItemsResponse
	4, // 7: grpc.TodoService.CreateTodoItem:output_type -> grpc.CreateTodoItemResponse
	6, // 8: grpc.TodoService.UpdateTodoItem:output_type -> grpc.UpdateTodoItemResponse
	8, // 9: grpc.TodoService.DeleteTodoItem:output_type -> grpc.DeleteTodoItemResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TodoItem_proto_init() }
func file_TodoItem_proto_init() {
	if File_TodoItem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TodoItem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTodoItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTodoItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTodoItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTodoItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTodoItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTodoItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TodoItem_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTodoItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TodoItem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TodoItem_proto_goTypes,
		DependencyIndexes: file_TodoItem_proto_depIdxs,
		MessageInfos:      file_TodoItem_proto_msgTypes,
	}.Build()
	File_TodoItem_proto = out.File
	file_TodoItem_proto_rawDesc = nil
	file_TodoItem_proto_goTypes = nil
	file_TodoItem_proto_depIdxs = nil
}
